class BaseApiException(Exception): ...


class InvalidInputException(BaseApiException): ...


class InvalidStateException(BaseApiException): ...


class InvalidStateException(BaseApiException): ...


class UnableToSaveException(BaseApiException): ...


class InvalidUserException(BaseApiException): ...


class InvalidTokenException(BaseApiException): ...


class ValueErrorException(BaseApiException): ...

class NotFoundException(BaseApiException): ...
